In [1]:
import numpy as np

print('1. Створення одновимірного масиву (вектора) з першими 10-ма натуральними числами та виведення його значення')
vector = np.arange(1, 11)
print("Вектор з першими 10-ма натуральними числами:", vector)

print('2. Створення двовимірного масиву (матриці) розміром 3x3, заповнення його нулями та виведення його значення')
matrix_3x3 = np.zeros((3, 3))
print("Матриця 3x3, заповнена нулями:\n", matrix_3x3)

print('3. Створення масиву розміром 5x5, заповнення його випадковими цілими числами в діапазоні від 1 до 10 та виведення його значення')
matrix_5x5 = np.random.randint(1, 11, (5, 5))
print("Матриця 5x5, заповнена випадковими цілими числами від 1 до 10:\n", matrix_5x5)

print('4. Створення масиву розміром 4x4, заповнення його випадковими дійсними числами в діапазоні від 0 до 1 та виведення його значення')
matrix_4x4 = np.random.random((4, 4))
print("Матриця 4x4, заповнена випадковими дійсними числами від 0 до 1:\n", matrix_4x4)

print('5. Створення двох одновимірних масивів розміром 5, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та виконання поелементних операцій додавання, віднімання та множення')
vector1 = np.random.randint(1, 11, 5)
vector2 = np.random.randint(1, 11, 5)
print("Перший вектор:", vector1)
print("Другий вектор:", vector2)
print("Поелементне додавання:", vector1 + vector2)
print("Поелементне віднімання:", vector1 - vector2)
print("Поелементне множення:", vector1 * vector2)

print('6. Створення двох векторів розміром 7, заповнення довільними числами та знаходження їх скалярного добутку')
vector3 = np.random.random(7)
vector4 = np.random.random(7)
print("Перший вектор:", vector3)
print("Другий вектор:", vector4)
print("Скалярний добуток:", np.dot(vector3, vector4))

print('7. Створення двох матриць розміром 2x2 та 2x3, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та перемноження їх між собою')
matrix_2x2 = np.random.randint(1, 11, (2, 2))
matrix_2x3 = np.random.randint(1, 11, (2, 3))
print("Матриця 2x2:\n", matrix_2x2)
print("Матриця 2x3:\n", matrix_2x3)
print("Добуток матриць:\n", np.dot(matrix_2x2, matrix_2x3))

print('8. Створення матриці розміром 3x3, заповнення її випадковими цілими числами в діапазоні від 1 до 10 та знаходження її оберненої матриці')
matrix_3x3_inv = np.random.randint(1, 11, (3, 3))
print("Матриця 3x3:\n", matrix_3x3_inv)
try:
    inverse_matrix = np.linalg.inv(matrix_3x3_inv)
    print("Обернена матриця 3x3:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Обернена матриця не існує")

print('9. Створення матриці розміром 4x4, заповнення її випадковими дійсними числами в діапазоні від 0 до 1 та транспонування її')
matrix_4x4_transpose = np.random.random((4, 4))
print("Матриця 4x4:\n", matrix_4x4_transpose)
print("Транспонована матриця 4x4:\n", np.transpose(matrix_4x4_transpose))

print('10. Створення матриці розміром 3x4 та вектора розміром 4, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та перемноження матриці на вектор')
matrix_3x4 = np.random.randint(1, 11, (3, 4))
vector5 = np.random.randint(1, 11, 4)
print("Матриця 3x4:\n", matrix_3x4)
print("Вектор розміром 4:", vector5)
print("Добуток матриці на вектор:", np.dot(matrix_3x4, vector5))

print('11. Створення матриці розміром 2x3 та вектора розміром 3, заповнення їх випадковими дійсними числами в діапазоні від 0 до 1 та перемноження матриці на вектор')
matrix_2x3 = np.random.random((2, 3))
vector6 = np.random.random(3)
print("Матриця 2x3:\n", matrix_2x3)
print("Вектор розміром 3:", vector6)
print("Добуток матриці на вектор:", np.dot(matrix_2x3, vector6))

print('12. Створення двох матриць розміром 2x2, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та виконання їхнього поелементного множення')
matrix_2x2_a = np.random.randint(1, 11, (2, 2))
matrix_2x2_b = np.random.randint(1, 11, (2, 2))
print("Перша матриця 2x2:\n", matrix_2x2_a)
print("Друга матриця 2x2:\n", matrix_2x2_b)
print("Поелементне множення:\n", np.multiply(matrix_2x2_a, matrix_2x2_b))

print('13. Створення двох матриць розміром 2x2, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та знаходження їх добутку')
print("Добуток матриць 2x2:\n", np.dot(matrix_2x2_a, matrix_2x2_b))

print('14. Створення матриці розміром 5x5, заповнення її випадковими цілими числами в діапазоні від 1 до 100 та знаходження суми елементів матриці')
matrix_5x5_sum = np.random.randint(1, 101, (5, 5))
print("Матриця 5x5:\n", matrix_5x5_sum)
print("Сума елементів матриці 5x5:", np.sum(matrix_5x5_sum))

print('15. Створення двох матриць розміром 4x4, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та знаходження їхньої різниці')
matrix_4x4_a = np.random.randint(1, 11, (4, 4))
matrix_4x4_b = np.random.randint(1, 11, (4, 4))
print("Перша матриця 4x4:\n", matrix_4x4_a)
print("Друга матриця 4x4:\n", matrix_4x4_b)
print("Різниця матриць 4x4:\n", matrix_4x4_a - matrix_4x4_b)

print('16. Створення матриці розміром 3x3, заповнення її випадковими дійсними числами в діапазоні від 0 до 1 та знаходження вектора-стовпчика, що містить суму елементів кожного рядка матриці')
matrix_3x3_sum = np.random.random((3, 3))
print("Матриця 3x3:\n", matrix_3x3_sum)
print("Вектор-стовпчик з сумою елементів кожного рядка:\n", np.sum(matrix_3x3_sum, axis=1).reshape(-1, 1))

print('17. Створення матриці розміром 3x4 з довільними цілими числами і створення матриці з квадратами цих чисел')
matrix_3x4_squares = np.random.randint(1, 11, (3, 4))
print("Матриця 3x4:\n", matrix_3x4_squares)
print("Матриця з квадратами чисел:\n", np.square(matrix_3x4_squares))

print('18. Створення вектора розміром 4, заповнення його випадковими цілими числами в діапазоні від 1 до 50 та знаходження вектора з квадратними коренями цих чисел')
vector7 = np.random.randint(1, 51, 4)
print("Вектор розміром 4:", vector7)
print("Вектор з квадратними коренями чисел:", np.sqrt(vector7))

1. Створення одновимірного масиву (вектора) з першими 10-ма натуральними числами та виведення його значення
Вектор з першими 10-ма натуральними числами: [ 1  2  3  4  5  6  7  8  9 10]
2. Створення двовимірного масиву (матриці) розміром 3x3, заповнення його нулями та виведення його значення
Матриця 3x3, заповнена нулями:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
3. Створення масиву розміром 5x5, заповнення його випадковими цілими числами в діапазоні від 1 до 10 та виведення його значення
Матриця 5x5, заповнена випадковими цілими числами від 1 до 10:
 [[ 2  2  3  2  8]
 [ 9  4  1  3  1]
 [ 4  8  8  5 10]
 [ 6  7  2  5  8]
 [ 7  8  2  4  3]]
4. Створення масиву розміром 4x4, заповнення його випадковими дійсними числами в діапазоні від 0 до 1 та виведення його значення
Матриця 4x4, заповнена випадковими дійсними числами від 0 до 1:
 [[0.42563299 0.09574174 0.304765   0.99339017]
 [0.85985468 0.47490161 0.31299248 0.05781103]
 [0.88106496 0.86692419 0.10994033 0.90084793]
 [0.72667344 0.018008