In [1]:
import numpy as np

In [2]:
print('1. Створення одновимірного масиву (вектора) з першими 10-ма натуральними числами та виведення його значення')
vector = np.arange(1, 11)
print("Вектор з першими 10-ма натуральними числами:", vector)

1. Створення одновимірного масиву (вектора) з першими 10-ма натуральними числами та виведення його значення
Вектор з першими 10-ма натуральними числами: [ 1  2  3  4  5  6  7  8  9 10]


In [3]:
print('2. Створення двовимірного масиву (матриці) розміром 3x3, заповнення його нулями та виведення його значення')
matrix_3x3 = np.zeros((3, 3))
print("Матриця 3x3, заповнена нулями:\n", matrix_3x3)

2. Створення двовимірного масиву (матриці) розміром 3x3, заповнення його нулями та виведення його значення
Матриця 3x3, заповнена нулями:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print('3. Створення масиву розміром 5x5, заповнення його випадковими цілими числами в діапазоні від 1 до 10 та виведення його значення')
matrix_5x5 = np.random.randint(1, 11, (5, 5))
print("Матриця 5x5, заповнена випадковими цілими числами від 1 до 10:\n", matrix_5x5)

3. Створення масиву розміром 5x5, заповнення його випадковими цілими числами в діапазоні від 1 до 10 та виведення його значення
Матриця 5x5, заповнена випадковими цілими числами від 1 до 10:
 [[5 6 9 2 8]
 [5 2 4 3 2]
 [5 3 9 4 2]
 [9 4 3 6 7]
 [1 8 4 8 5]]


In [5]:
print('4. Створення масиву розміром 4x4, заповнення його випадковими дійсними числами в діапазоні від 0 до 1 та виведення його значення')
matrix_4x4 = np.random.random((4, 4))
print("Матриця 4x4, заповнена випадковими дійсними числами від 0 до 1:\n", matrix_4x4)

4. Створення масиву розміром 4x4, заповнення його випадковими дійсними числами в діапазоні від 0 до 1 та виведення його значення
Матриця 4x4, заповнена випадковими дійсними числами від 0 до 1:
 [[0.51364495 0.42949316 0.61994779 0.35393257]
 [0.52207078 0.06761989 0.08998065 0.22222678]
 [0.12630128 0.00673759 0.79599292 0.61736705]
 [0.61446083 0.28447913 0.00560642 0.62591562]]


In [6]:
print('5. Створення двох одновимірних масивів розміром 5, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та виконання поелементних операцій додавання, віднімання та множення')
vector1 = np.random.randint(1, 11, 5)
vector2 = np.random.randint(1, 11, 5)
print("Перший вектор:", vector1)
print("Другий вектор:", vector2)
print("Поелементне додавання:", vector1 + vector2)
print("Поелементне віднімання:", vector1 - vector2)
print("Поелементне множення:", vector1 * vector2)

5. Створення двох одновимірних масивів розміром 5, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та виконання поелементних операцій додавання, віднімання та множення
Перший вектор: [1 9 5 2 9]
Другий вектор: [6 5 8 2 3]
Поелементне додавання: [ 7 14 13  4 12]
Поелементне віднімання: [-5  4 -3  0  6]
Поелементне множення: [ 6 45 40  4 27]


In [7]:
print('6. Створення двох векторів розміром 7, заповнення довільними числами та знаходження їх скалярного добутку')
vector3 = np.random.random(7)
vector4 = np.random.random(7)
print("Перший вектор:", vector3)
print("Другий вектор:", vector4)
print("Скалярний добуток:", np.dot(vector3, vector4))

6. Створення двох векторів розміром 7, заповнення довільними числами та знаходження їх скалярного добутку
Перший вектор: [0.32769923 0.00768632 0.63540169 0.72425693 0.98823733 0.68171711
 0.64102476]
Другий вектор: [0.49735345 0.01333033 0.49354601 0.47763819 0.14304267 0.2656173
 0.13913017]
Скалярний добуток: 1.234239386575781


In [8]:
print('7. Створення двох матриць розміром 2x2 та 2x3, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та перемноження їх між собою')
matrix_2x2 = np.random.randint(1, 11, (2, 2))
matrix_2x3 = np.random.randint(1, 11, (2, 3))
print("Матриця 2x2:\n", matrix_2x2)
print("Матриця 2x3:\n", matrix_2x3)
print("Добуток матриць:\n", np.dot(matrix_2x2, matrix_2x3))

7. Створення двох матриць розміром 2x2 та 2x3, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та перемноження їх між собою
Матриця 2x2:
 [[ 6  4]
 [10  9]]
Матриця 2x3:
 [[8 4 9]
 [8 6 3]]
Добуток матриць:
 [[ 80  48  66]
 [152  94 117]]


In [9]:
print('8. Створення матриці розміром 3x3, заповнення її випадковими цілими числами в діапазоні від 1 до 10 та знаходження її оберненої матриці')
matrix_3x3_inv = np.random.randint(1, 11, (3, 3))
print("Матриця 3x3:\n", matrix_3x3_inv)
try:
    inverse_matrix = np.linalg.inv(matrix_3x3_inv)
    print("Обернена матриця 3x3:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Обернена матриця не існує")

8. Створення матриці розміром 3x3, заповнення її випадковими цілими числами в діапазоні від 1 до 10 та знаходження її оберненої матриці
Матриця 3x3:
 [[4 3 6]
 [9 8 8]
 [8 1 2]]
Обернена матриця 3x3:
 [[-5.00000000e-02  2.46716228e-17  1.50000000e-01]
 [-2.87500000e-01  2.50000000e-01 -1.37500000e-01]
 [ 3.43750000e-01 -1.25000000e-01 -3.12500000e-02]]


In [10]:
print('9. Створення матриці розміром 4x4, заповнення її випадковими дійсними числами в діапазоні від 0 до 1 та транспонування її')
matrix_4x4_transpose = np.random.random((4, 4))
print("Матриця 4x4:\n", matrix_4x4_transpose)
print("Транспонована матриця 4x4:\n", np.transpose(matrix_4x4_transpose))

9. Створення матриці розміром 4x4, заповнення її випадковими дійсними числами в діапазоні від 0 до 1 та транспонування її
Матриця 4x4:
 [[0.53224197 0.00358329 0.37142828 0.68073755]
 [0.96891874 0.6776069  0.40052468 0.18964403]
 [0.85638092 0.85752367 0.30850823 0.51344671]
 [0.69310769 0.01233362 0.06010369 0.01930979]]
Транспонована матриця 4x4:
 [[0.53224197 0.96891874 0.85638092 0.69310769]
 [0.00358329 0.6776069  0.85752367 0.01233362]
 [0.37142828 0.40052468 0.30850823 0.06010369]
 [0.68073755 0.18964403 0.51344671 0.01930979]]


In [11]:
print('10. Створення матриці розміром 3x4 та вектора розміром 4, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та перемноження матриці на вектор')
matrix_3x4 = np.random.randint(1, 11, (3, 4))
vector5 = np.random.randint(1, 11, 4)
print("Матриця 3x4:\n", matrix_3x4)
print("Вектор розміром 4:", vector5)
print("Добуток матриці на вектор:", np.dot(matrix_3x4, vector5))

10. Створення матриці розміром 3x4 та вектора розміром 4, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та перемноження матриці на вектор
Матриця 3x4:
 [[ 2  4  9 10]
 [ 4  1  3  2]
 [ 9  9  4  7]]
Вектор розміром 4: [4 4 3 3]
Добуток матриці на вектор: [ 81  35 105]


In [12]:
print('11. Створення матриці розміром 2x3 та вектора розміром 3, заповнення їх випадковими дійсними числами в діапазоні від 0 до 1 та перемноження матриці на вектор')
matrix_2x3 = np.random.random((2, 3))
vector6 = np.random.random(3)
print("Матриця 2x3:\n", matrix_2x3)
print("Вектор розміром 3:", vector6)
print("Добуток матриці на вектор:", np.dot(matrix_2x3, vector6))

11. Створення матриці розміром 2x3 та вектора розміром 3, заповнення їх випадковими дійсними числами в діапазоні від 0 до 1 та перемноження матриці на вектор
Матриця 2x3:
 [[0.64554826 0.69679615 0.25956318]
 [0.6355264  0.36007619 0.87726593]]
Вектор розміром 3: [0.89398585 0.42629745 0.43037074]
Добуток матриці на вектор: [0.98586183 1.09920076]


In [13]:
print('12. Створення двох матриць розміром 2x2, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та виконання їхнього поелементного множення')
matrix_2x2_a = np.random.randint(1, 11, (2, 2))
matrix_2x2_b = np.random.randint(1, 11, (2, 2))
print("Перша матриця 2x2:\n", matrix_2x2_a)
print("Друга матриця 2x2:\n", matrix_2x2_b)
print("Поелементне множення:\n", np.multiply(matrix_2x2_a, matrix_2x2_b))

12. Створення двох матриць розміром 2x2, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та виконання їхнього поелементного множення
Перша матриця 2x2:
 [[2 7]
 [2 4]]
Друга матриця 2x2:
 [[ 1  6]
 [ 9 10]]
Поелементне множення:
 [[ 2 42]
 [18 40]]


In [14]:
print('13. Створення двох матриць розміром 2x2, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та знаходження їх добутку')
print("Добуток матриць 2x2:\n", np.dot(matrix_2x2_a, matrix_2x2_b))

13. Створення двох матриць розміром 2x2, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та знаходження їх добутку
Добуток матриць 2x2:
 [[65 82]
 [38 52]]


In [15]:
print('14. Створення матриці розміром 5x5, заповнення її випадковими цілими числами в діапазоні від 1 до 100 та знаходження суми елементів матриці')
matrix_5x5_sum = np.random.randint(1, 101, (5, 5))
print("Матриця 5x5:\n", matrix_5x5_sum)
print("Сума елементів матриці 5x5:", np.sum(matrix_5x5_sum))

14. Створення матриці розміром 5x5, заповнення її випадковими цілими числами в діапазоні від 1 до 100 та знаходження суми елементів матриці
Матриця 5x5:
 [[ 7  2 13 27 66]
 [47 21  4 32 39]
 [99 37 78 62 37]
 [91 35 66 88 80]
 [32 69 67  6 30]]
Сума елементів матриці 5x5: 1135


In [16]:
print('15. Створення двох матриць розміром 4x4, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та знаходження їхньої різниці')
matrix_4x4_a = np.random.randint(1, 11, (4, 4))
matrix_4x4_b = np.random.randint(1, 11, (4, 4))
print("Перша матриця 4x4:\n", matrix_4x4_a)
print("Друга матриця 4x4:\n", matrix_4x4_b)
print("Різниця матриць 4x4:\n", matrix_4x4_a - matrix_4x4_b)

15. Створення двох матриць розміром 4x4, заповнення їх випадковими цілими числами в діапазоні від 1 до 10 та знаходження їхньої різниці
Перша матриця 4x4:
 [[4 5 1 3]
 [2 3 6 4]
 [5 3 1 5]
 [2 5 7 4]]
Друга матриця 4x4:
 [[2 2 4 1]
 [5 1 1 7]
 [1 8 9 3]
 [5 5 3 4]]
Різниця матриць 4x4:
 [[ 2  3 -3  2]
 [-3  2  5 -3]
 [ 4 -5 -8  2]
 [-3  0  4  0]]


In [17]:
print('16. Створення матриці розміром 3x3, заповнення її випадковими дійсними числами в діапазоні від 0 до 1 та знаходження вектора-стовпчика, що містить суму елементів кожного рядка матриці')
matrix_3x3_sum = np.random.random((3, 3))
print("Матриця 3x3:\n", matrix_3x3_sum)
print("Вектор-стовпчик з сумою елементів кожного рядка:\n", np.sum(matrix_3x3_sum, axis=1).reshape(-1, 1))

16. Створення матриці розміром 3x3, заповнення її випадковими дійсними числами в діапазоні від 0 до 1 та знаходження вектора-стовпчика, що містить суму елементів кожного рядка матриці
Матриця 3x3:
 [[0.76947856 0.96833597 0.38902395]
 [0.74555189 0.18020721 0.48030438]
 [0.01344481 0.23072349 0.1499609 ]]
Вектор-стовпчик з сумою елементів кожного рядка:
 [[2.12683847]
 [1.40606348]
 [0.39412919]]


In [18]:
print('17. Створення матриці розміром 3x4 з довільними цілими числами і створення матриці з квадратами цих чисел')
matrix_3x4_squares = np.random.randint(1, 11, (3, 4))
print("Матриця 3x4:\n", matrix_3x4_squares)
print("Матриця з квадратами чисел:\n", np.square(matrix_3x4_squares))

17. Створення матриці розміром 3x4 з довільними цілими числами і створення матриці з квадратами цих чисел
Матриця 3x4:
 [[ 6  8  5  9]
 [ 1  9 10  5]
 [ 6  3  2 10]]
Матриця з квадратами чисел:
 [[ 36  64  25  81]
 [  1  81 100  25]
 [ 36   9   4 100]]


In [19]:
print('18. Створення вектора розміром 4, заповнення його випадковими цілими числами в діапазоні від 1 до 50 та знаходження вектора з квадратними коренями цих чисел')
vector7 = np.random.randint(1, 51, 4)
print("Вектор розміром 4:", vector7)
print("Вектор з квадратними коренями чисел:", np.sqrt(vector7))

18. Створення вектора розміром 4, заповнення його випадковими цілими числами в діапазоні від 1 до 50 та знаходження вектора з квадратними коренями цих чисел
Вектор розміром 4: [13 23 29 32]
Вектор з квадратними коренями чисел: [3.60555128 4.79583152 5.38516481 5.65685425]
